name: Update Paper List
on:
  schedule:
    - cron: "0 * * * 1-5"
  workflow_dispatch:
    inputs:
      target_date:
        description: "Target date %y-%m-%d"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: |
          if [ -n "${{ github.event.inputs.target_date }}" ]; then
            python update_arxiv_list.py --target_date=${{ github.event.inputs.target_date }}
          else
            python update_arxiv_list.py
          fi
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Commit and push
        run: |
          git config --local user.email "yjgwak.cs@github.com"
          git config --local user.name "Update arxiv RL list"
          git add .
          git commit -m "Update paper list" -a || exit 0
          git push origin HEAD:master || exit 0
